services:
  postgres:
    image: postgres:15
    container_name: ledger_postgres
    environment:
      POSTGRES_DB: ledger_db
      POSTGRES_USER: ledger_user
      POSTGRES_PASSWORD: ledger_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledger_user -d ledger_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    mem_limit: 512m

  redis:
    image: redis:7.2-alpine
    container_name: ledger_redis
    ports:
      - "6380:6379"
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    mem_limit: 256m

volumes:
  postgres_data: